---
jupyter:
  jupytext:
    formats: ipynb,R:percent,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.8.1
  kernelspec:
    display_name: R
    language: R
    name: ir
---

# Animations and Interactivity

## PUT YOUR NAME HERE: Marcio Woitek

```{r setup, include=FALSE}
library(tidyverse)
library(gganimate)
library(gifski)
library(plotly)
```

## Problem 1

```{r problem_1_data, include=FALSE}
Category <- c("Alpha", "Beta", "Zeta")
City <- c("Hong Kong", "London", "Nairobi")
my_dat <- expand_grid(Category, City)
set.seed(84684)
my_dat$Value <- sample(1:10, 9, replace = T)
```

```{r problem_1, echo=FALSE, message=FALSE}
# Put your ggplot figure with the appropriate gganimate functions here.
```

## Problem 2

```{r problem_2_data, include=FALSE}
Response <- c("Energize", "Amazing", "Great")
set.seed(9819)
Energize <- tibble(
    Company = rep("Energize", 100),
    Output = rnorm(100, 50, 20)
)
set.seed(9819)
Amazing <- tibble(
    Company = rep("Amazing", 100),
    Output = rnorm(100, 50, 10)
)
set.seed(9819)
Great <- tibble(
    Company = rep("Great", 100),
    Output = rnorm(100, 40, 5)
)
my_dat <- bind_rows(Energize, Amazing, Great)
```

```{r problem_2, echo=FALSE, message=FALSE, warning=FALSE}
# Put your ggplotly() figure here.
```

## Problem 3

```{r problem_3_data, echo=FALSE, message=FALSE, warning=FALSE}
Category <- seq(from = 1, to = 10)
Time <- seq(from = 1, to = 10)
dat3 <- expand_grid(Category, Time)
set.seed(78957)
dat3$Quantity <- runif(100, 0, 10)
```

```{r problem_3, echo=FALSE, message=FALSE, warning=FALSE}
# Put your ggplotly() figure here.
```
