---
jupyter:
  jupytext:
    formats: ipynb,R:percent,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.8.1
  kernelspec:
    display_name: R
    language: R
    name: ir
---

# Spatial Figures Peer Review

## PUT YOUR NAME HERE: Marcio Woitek

```{r setup, include=FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(maps))
suppressPackageStartupMessages(library(sf))
suppressPackageStartupMessages(library(rnaturalearth))
suppressPackageStartupMessages(library(rnaturalearthdata))
suppressPackageStartupMessages(library(rgeos))
```

## Problem 1

Create the figure using the data included in the R Markdown file.

```{r problem_1_data, include=FALSE}
# Make some data for painting the map:
my_world_map <- map_data("world")
countries <- unique(my_world_map$region)
set.seed(987)
some_data_values <- data.frame(
    "Region" = countries,
    "Score" = runif(252, 0, 100)
)
```

```{r problem_1, echo=FALSE, message=FALSE}
# scale_fill_distiller(palette = 5)
# Use left_join to combine the data_values to the world map data in
# my_world_map.
```

## Problem 2

Create the figure using the data included in the R Markdown file.

```{r problem_2_data, include=FALSE}
set.seed(15)
Measurement <- rnorm(32, 50, 1)
```

```{r problem_2, echo=FALSE, message=FALSE}
# Get just the maps of Costa Rica, Panama and Nicaragua.
# Put in points only for cities with a population of greater than 40,000. This
# should leave you with 32 cities.
# Use add_column to attach the "Measurement" variable to your data, and set
# that to the color aesthetic when you draw the points.
# Set the colors for the city points with scale_color_distiller(palette = 7).
# Set the size of all points to 5.
```

## Problem 3

Create the figure using the data included in the R Markdown file.

```{r problem_3_data, include=FALSE}
s_america <- ne_countries(
    scale = "medium",
    continent = "south america",
    returnclass = "sf"
)
```

```{r problem_3, echo=FALSE}
# The s_america object created in the chunk above is a simple features object
# with many columns. Identify the correct column based on the solution figure
# and use it to color in the choropleth.
# scale_fill_distiller(palette = 10)
```
